spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.epam.serdes.CustomDeserializer
    streams:
      application-id: kafka-steams
      bootstrap-servers: localhost:9092
      properties:
        default:
          deserialization:
            exception:
              handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler